

services:
  tickets-system-api:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    image: appointments-api-docker
    container_name: tickets-system-api
    restart: always
    command: npm run start:dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/app
  
  db:
    image: postgres:16.2
    container_name: tickets-system-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  pgdata:
    driver: local
